### ISSUE TITLE
Representative

### ISSUE THREAD

**Issue by bentilly** [bentilly/heroes#1]
#### As a viewer, I can see a list of REPRESENTATIVES for each SPORT

Reference the current code for SPORT but you are welcome to use a different structure or pattern if you think it will be better.

Work on the DEVELOPMENT branch. We will merge up to master later.

Cheers

Ben

**Comment by crchemist** [comment]
@bentilly I think first we need to setup some basic stuff for represent Users and Roles before implementing some certain models, what do you think about that?
