### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by bentilly** [bentilly/heroes#46]
We need to be able to record where a Squad placed in a competition. This is tricky as it involves Trophies and there may be several results for a single event:

eg:
EVENT = 2014 World Championships
TROPHIES (competed for at the event) = [Best in the World,  The Tilly-Kharechko Cup]

Everyone at the event competes for the Best in the World, but some games count towards the T-K Cup.

Also, age group trophies counld be linked to a DIVISION (but not compulsory). EG: at the World Champs, there are 4 Trophies, Elite, Womens, U19 Boys and U19 Girls.

I think we could do something like...

Link Trophies to an Event. Under each event-trophie there would be a list of the Squads that competed for that trophy at that event. The list could then be ordered with the winner at the top. (Need to allow draws (eg "3rd=") and 'no-result' (pulled out, disqualified)
#### Best in the World Mens (TROPHIE)

**results**
NZL mens team - 1st 
UKR mens team - 2nd
FRA mens team - 3rd
#### Best in the World Womens (TROPHIE)

**results**
UKR womens team - 1st
FRA womens team - 2nd
NZL womens team - 3rd
#### Tilly-Kharechko Cup (TROPHIE) (not linked to division)

**results**
UKR mens team - 1st
NZL womens team - 2nd

BEN - TODO: Draw a picture

**Comment by crchemist** [comment]
@bentilly can you make some wireframe for this task?

**Comment by bentilly** [comment]
Ive added some HTML as an example.
templates/examples/event.html
templates/examples/eventtrophy.html

**Comment by bentilly** [comment]
- Dont worry about trophies with no division. Lets make all trophies have a division.
- No (eg) "2nd =" placings. Results are 1, 2, 3, 4... n
