### ISSUE TITLE
admin panel for ndb models

### ISSUE THREAD

**Issue by crchemist** [bentilly/heroes#7]
Implement tiny interface for admin CRUD on models. Something like https://github.com/vsergeyev/ndbadmin

**Comment by bentilly** [comment]
That could be very cool. Will it handle dependencies like selecting other objects? eg, when making a TEAM you select a COUNTRY and DIVISION, which will have to be lists from the datastore.

**Comment by crchemist** [comment]
@bentilly 

> Will it handle dependencies like selecting other objects?

Yes, I think so. At this moment I connected https://github.com/vsergeyev/ndbadmin on /admin/ path, but not yet added our models to it. Plan to do it at Sunday.
