### ISSUE TITLE
Add 'Team' model 

### ISSUE THREAD

**Issue by crchemist** [bentilly/heroes#8]

**Comment by bentilly** [comment]
I think in pictures. Would it help if I created wireframes as we go? Give you a basic UI to work towards. 
![index](https://cloud.githubusercontent.com/assets/431583/8943711/2dc3c1e2-35d0-11e5-9816-313f74e18ef1.png)
![sport](https://cloud.githubusercontent.com/assets/431583/8943712/2dc438f2-35d0-11e5-9ade-b88bb797c0f7.png)

See attached.

**Comment by crchemist** [comment]
@bentilly verrrry thanks for wireframes. They really helpful and I think speed up development in several times.

**Comment by bentilly** [comment]
Updated wireframes. Ill keep working on these as we go

https://invis.io/9M3QYVGG6
